- hosts: master
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: test-cluster
      cluster.initial_master_nodes: elasticmaster
      http.port: 9200
      network.host: elasticmaster
      node.roles: ["master", "data"]
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: data
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_heap_size: "128m"
    es_config:
      cluster.name: "test-cluster"
      discovery.seed_hosts: "elasticmaster:9300"
      network.host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      http.port: 9200
      node.roles: ["data"]
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment
